export const MainData = [
  { title: "مامور توضیع", name: "admin/Dispacher" },
  { title: "  ثبت محصول جدید ", name: "admin/Product-Registration" },
  { title: "ویرایش محصول", name: "admin/Edit" },
  { title: " شارژ کالا", name: "admin/Charge " },
  { title: "ثبت کاربر ارگانی", name: "admin/Buyer-User-Registration" },
  { title: " ثبت کاربر سیستم", name: "admin/System-User-Registration" },
  { title: "آماده سازی و پردازش", name: "admin/Processing" },
  { title: "صدور فاکتور", name: "admin/Bill" },
  { title: " مدیریت فروشگاه ", name: "admin/Store-Registration" },
  // { title: " مدیریت دسترسی", name: "Access-Management" },
  // { title: " ایجاد دسترسی ", name: "Create-Access" },
  // { title: " اطلاعات کاربران ", name: "User-Information" },
  // { title: " ثبت ارگان ", name: "Organization-Registration" },
  // { title: " انبار گرددانی ", name: "Warehouse-Handling" },
  // { title: " اطلاعات انبار ", name: "Warehouse-Information" },
  // { title: " سابقه خرید ", name: "History" },
  // { title: " سفارش ها   ", name: "Orders" },
  // { title: " بایگانی شده ", name: "Archive" },
  // { title: " اطلاع رسانی ", name: "Notices" },
  // { title: " مدیریت برنامه ", name: "Program-Management" },
  // { title: " تبلغات ", name: "Advertise" },
  // { title: " کدتخفیف ", name: "Discount-Code" },
  // { title: " آمار و پایش داده  ", name: "Data-Monitoring" },
  // { title: " مدیریت کارکنان ", name: "Employee-Management" },
  // { title: " انبار فروشگاه ", name: "Store-arehouse" },
];
